version: '3.8'
services:
    app:
        build: .
        environment:
            MAILER_DSN: 'smtp://mailhog:1025'
        depends_on:
            - mailhog

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"   # SMTP port
            - "8025:8025"   # Web UI port
